<?php
/**
 * Front controller for payment gateway browser returns.
 *
 * @package WPEMS\Payments
 * @since   3.0.0
 */

namespace WPEMS\Payments;

defined( 'ABSPATH' ) || exit;

use Throwable;
use WPEMS\Repositories\BookingRepository;
use WPEMS\Services\PaymentSyncService;

/**
 * Handles `wpems_gateway` return/cancel URLs generated by payment gateways.
 */
final class PaymentReturnRouter {

	/**
	 * Whether hooks have been registered.
	 *
	 * @var bool
	 */
	private static bool $bootstrapped = false;

	/**
	 * Register WordPress hooks.
	 *
	 * @return void
	 */
	public static function bootstrap(): void {
		if ( self::$bootstrapped ) {
			return;
		}

		self::$bootstrapped = true;

		add_action( 'template_redirect', array( self::class, 'dispatch' ), 0 );
	}

	/**
	 * Dispatch the current browser return request.
	 *
	 * @return void
	 */
	public static function dispatch(): void {
		$redirect_url = self::handle_request( $_GET );

		if ( null === $redirect_url ) {
			return;
		}

		wp_safe_redirect( $redirect_url );
		exit;
	}

	/**
	 * Handle a request array without redirecting.
	 *
	 * @param array $request Request data, usually $_GET.
	 *
	 * @return string|null Redirect URL when handled; null when not a payment return.
	 */
	public static function handle_request( array $request ): ?string {
		$request    = self::sanitize_request( $request );
		$gateway_id = (string) ( $request['wpems_gateway'] ?? '' );

		if ( '' === $gateway_id ) {
			return null;
		}

		$booking_id = (int) ( $request['booking_id'] ?? 0 );
		$gateway    = PaymentGatewayRegistry::instance()->get( $gateway_id );

		if ( null === $gateway ) {
			return self::order_received_url( $booking_id, PaymentResult::STATUS_UNKNOWN, 'gateway_not_found' );
		}

		try {
			$result = $gateway->handle_return_request( $request );
			self::apply_result_if_possible( $result );

			return self::order_received_url(
				$result->get_booking_id() > 0 ? $result->get_booking_id() : $booking_id,
				$result->get_status(),
				$result->get_message()
			);
		} catch ( Throwable $e ) {
			return self::order_received_url( $booking_id, PaymentResult::STATUS_UNKNOWN, 'gateway_return_error' );
		}
	}

	/**
	 * Sanitize request data before it reaches gateway handlers.
	 *
	 * @param array $request Request data.
	 *
	 * @return array
	 */
	private static function sanitize_request( array $request ): array {
		$sanitized = array();

		foreach ( $request as $key => $value ) {
			$key = sanitize_key( wp_unslash( $key ) );
			if ( '' === $key ) {
				continue;
			}

			$sanitized[ $key ] = self::sanitize_value( $value );
		}

		if ( isset( $sanitized['wpems_gateway'] ) ) {
			$sanitized['wpems_gateway'] = sanitize_key( $sanitized['wpems_gateway'] );
		}
		if ( isset( $sanitized['action'] ) ) {
			$sanitized['action'] = sanitize_key( $sanitized['action'] );
		}
		if ( isset( $sanitized['booking_id'] ) ) {
			$sanitized['booking_id'] = absint( $sanitized['booking_id'] );
		}

		return $sanitized;
	}

	/**
	 * Recursively sanitize one request value.
	 *
	 * @param mixed $value Request value.
	 *
	 * @return mixed
	 */
	private static function sanitize_value( $value ) {
		$value = wp_unslash( $value );

		if ( is_array( $value ) ) {
			return array_map( array( self::class, 'sanitize_value' ), $value );
		}

		return sanitize_text_field( $value );
	}

	/**
	 * Apply a gateway return result through the payment sync service.
	 *
	 * @param PaymentResult $result Payment result.
	 *
	 * @return void
	 */
	private static function apply_result_if_possible( PaymentResult $result ): void {
		if ( $result->get_booking_id() <= 0 ) {
			return;
		}

		$booking = ( new BookingRepository() )->find( $result->get_booking_id() );
		if ( null === $booking ) {
			return;
		}

		PaymentSyncService::instance()->apply_result( $booking, $result, 'return' );
	}

	/**
	 * Build the local order-received redirect URL.
	 *
	 * @param int    $booking_id Booking ID.
	 * @param string $status     Payment status.
	 * @param string $message    Optional message code.
	 *
	 * @return string
	 */
	private static function order_received_url( int $booking_id, string $status, string $message = '' ): string {
		$args = array(
			'wpems'          => 'order-received',
			'payment_status' => sanitize_key( $status ),
		);

		if ( $booking_id > 0 ) {
			$args['booking_id'] = $booking_id;
		}
		if ( '' !== $message ) {
			$args['payment_message'] = sanitize_key( $message );
		}

		return add_query_arg( $args, home_url( '/' ) );
	}
}
